### ISSUE TITLE
Dependency was not found after installed.

### ISSUE THREAD

**Issue by l2D** [ivodolenc/nuxt-lazysizes#1]
` ERROR  Failed to compile with 1 errors                                              friendly-errors 22:57:24

This dependency was not found:                                                       friendly-errors 22:57:24
                                                                                     friendly-errors 22:57:24
* lazysizes in ./.nuxt/lazySizes.js`

buildModules
`buildModules: [
    '@nuxtjs/eslint-module',
    '@nuxtjs/tailwindcss',
    'nuxt-lazysizes',
  ],`

**Comment by ivodolenc** [comment]
Hi, I just tested `nuxt-lazysizes` (v1.1.2) with the latest `Nuxt` (v2.14.12) and it works fine.

Can you provide a link to the repo or codesandbox?

**Comment by l2D** [comment]
I'm sorry for the misunderstanding. This problem solved after I reinstall the package and Its work fine.

`+ nuxt-lazysizes@1.1.2
updated 1 package and moved 1 package in 7.016s`

But I don't know why when adding lazyload class. It's showing a broken image icon and text 'Background' when I hover on it. (The images work on the second hover but sometimes it's not working for the first time.)

https://user-images.githubusercontent.com/20911264/102835157-896dff00-4428-11eb-97df-e6ca1e98ee09.mp4

**Comment by ivodolenc** [comment]
> But I don't know why when adding lazyload class. It's showing a broken image icon and text 'Background' when I hover on it. (The images work on the second hover but sometimes it's not working for the first time.)

Not sure, but I don’t think it’s directly related to the package. 

> Edit1: I share the repo through your email.

Please create a reproduction (link to the code) that shows the issue.

**Comment by ivodolenc** [comment]
I'll close the issue due to inactivity. Feel free to reopen it with an attached link to a minimal reproduction that shows the issue.
