### ISSUE TITLE
NUXT 3 Support?

### ISSUE THREAD

**Issue by kosmeln** [ivodolenc/nuxt-lazysizes#10]
Hello there! 
Could anybody shed some light about **NUXT 3** support? Is this already in the works? Any ETA if so?
Any information would be appreciate as we'd really love to stick to lazy sizes in after our **NUXT 3** migration. Thanks :)

**Comment by ivodolenc** [comment]
Hi,

Thanks for your interest in this module.

I believe `Nuxt3` is still in `beta`, so let's wait for the first official `production-ready` version.

After that, I will adjust the module according to official guidelines to support the latest version.

But hey, good news is that the `module` works fine in `Nuxt2` projects 😃 👌

For now, you can manually import `lazysizes` to your `Nuxt3` project.

**Comment by vpiskunov** [comment]
Hey, is it worth revisiting Nuxt3 support? 

Out of beta since Nov 2022 - https://nuxt.com/blog/v3

Happy to contribute if someone knows the general idea of how to port it over? 

Or any other temporary solution for Nuxt3 compatible lazysizes option? 

Thanks!

**Comment by ivodolenc** [comment]
@vpiskunov Hey, this is not currently in process, but open to suggestions.

If you're interested in contributing, feel free to send a PR, I'll be sure to review and help update the module if needed.
