### ISSUE TITLE
Loading assets from static folder broken on nuxt2 bridge

### ISSUE THREAD

**Issue by thisismydesign** [ivodolenc/nuxt-lazysizes#14]
I'm updating a project to nuxt2 bridge and this broke images loaded from the static via `lazysizes` (getting 404s). My current workaround is to load from the assets folder as explained in https://github.com/ivodolenc/nuxt-lazysizes#advanced-usage-optional.

**Comment by ivodolenc** [comment]
Hi, thanks for the report but unfortunately the module is not compatible with Bridge or Nuxt 3 so this is kind of expected behavior. 

Also, one of the alternative is to directly import Lazysizes into the bridge or v3 projects. 

For now, the module works only in Nuxt 2 setup.

**Comment by thisismydesign** [comment]
Got it, thanks!
