### ISSUE TITLE
Are lazysizes plugins also supported with this module?

### ISSUE THREAD

**Issue by davision** [ivodolenc/nuxt-lazysizes#2]
I would like to use data-bg option for lazy loading background images. Is this currently possible with nuxt-lazysizes?

**Comment by ivodolenc** [comment]
> I would like to use data-bg option for lazy loading background images.

Hi, unfortunately at the moment this is not possible without additional configuration.

But I think I’ll add a feature that will give you the ability to enable desired lazy-plugins.

For now, you can try something like this:

Create a new `lazyBg.client.js` file in the `plugins/` directory.

```js
// plugins/lazyBg.client.js

import lazyBg from 'lazysizes/plugins/unveilhooks/ls.unveilhooks'
export default lazyBg
```

Enable it in the `nuxt.config.js`

```js
// nuxt.config.js

{
  plugins: [
    '~/plugins/lazyBg.client.js'
  ],
}
```

Use `data-bg` attribute to lazyload background images

```html
<div class="lazyload" data-bg="bg-img.jpg"></div>
```

**Comment by davision** [comment]
That would be great. Thanks for the tip. Nice work thou!

**Comment by ivodolenc** [comment]
I’ve added a new `plugins` feature so you can easily extend the default lazysizes `config` and enable additional plugins. 

For example, if you want to use the `data-bg` option, simply enable the `unveilhooks` plugin in `nuxt.config.js`:

```js
// nuxt.config.js

{
  lazySizes: {
    plugins: {
      unveilhooks: true
    },
  }
}
```

Available in: `1.2.0`
Docs: [Extra plugins (optional)](https://github.com/ivodolenc/nuxt-lazysizes#extra-plugins-optional)
Examples: [Plugins](https://github.com/ivodolenc/nuxt-lazysizes/tree/master/examples/plugins)

**Comment by davision** [comment]
That's awesome. Thank you very much.

**Comment by ivodolenc** [comment]
No problem, glad to help.

I'll close this because a new `plugins` feature has been added which resolves this request.
