### ISSUE TITLE
Non-lazyloaded images are 404 (Not Found) after setting up extendAssetUrls in nuxt.config.js

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [ivodolenc/nuxt-lazysizes#3]
I added these lines in my `nuxt.config.js` file as mentioned in the doc, to make the `~assets` calls work  :

```
lazySizes: {
    extendAssetUrls: {
      img: 'data-src',
      source: 'data-srcset',

      // Component with custom props
      AppImage: ['source-md-url', 'image-url'],
    },
  },
```

but now all my non-lazyloaded images (with regular `src` tags) are getting 404 Not Found.

Lazyloaded images are working correctly. But would it be possible tu support both lazyloaded and non-lazyloaded?

Thanks!

**Comment by ivodolenc** [comment]
Hi, when you use `extendAssetUrls` option, you must specify all attributes (default and custom) that will be used to load resources from `~/assets` directory.

This is Nuxt's `loader` default behavior and isn't a module issue. Don't get me wrong, everything works as expected you just need to define it properly.

Try this example:

```js
// nuxt.config.js

export default {
  lazySizes: {
    extendAssetUrls: {
      img: ['src', 'srcset', 'data-src', 'data-srcset'], // Add 'src' and 'srcset'
      source: ['src', 'srcset', 'data-src', 'data-srcset'], // Add 'src' and 'srcset'

      // You don't need this (example for a custom component)
      // AppImage: ['source-md-url', 'image-url'],
    },
  },
}
```

Let me know if everything works 😉

**Comment by MaxVeilleuxMTL** [comment]
Thanks @ivodolenc it's working great !

Cheers

**Comment by ivodolenc** [comment]
No problem, glad to help.

I will also update the docs to remove possible confusion.

Closing this as resolved.
