### ISSUE TITLE
Additional Plugins like parent-fit

### ISSUE THREAD

**Issue by theDevelopper** [ivodolenc/nuxt-lazysizes#5]
Hey, I see you support plugins, but it seems like only these three: blurUp, nativeLoading, unveilhooks.
How do I enable the parent-fit plugin? Or any other?

**Comment by ivodolenc** [comment]
Hi, thanks for your interest in this module. You can follow [this](https://github.com/ivodolenc/nuxt-lazysizes/issues/2#issuecomment-756756155) comment (a few easy steps) and add support for any additional plugin you want.

I will add support for other plugins as well. In the meantime, feel free to take a look and maybe create `PR` as new `feature` (add support for other plugins).

**Comment by ivodolenc** [comment]
Hey @theDevelopper @PavelZhuravlev, I just added support for [`parent-fit`](https://github.com/ivodolenc/nuxt-lazysizes#parent-fit-plugin) and [`rias`](https://github.com/ivodolenc/nuxt-lazysizes#rias-plugin-responsive-image-as-a-service--responsive-image-on-demand) extra plugins.

Available in the latest version: `1.3.0`

Closing this as resolved.

**Comment by PavelZhuravlev** [comment]
@ivodolenc Thank you!

**Comment by PavelZhuravlev** [comment]
@ivodolenc Thank you again, i have successfully added `rias` plugin into my project!
Is there any chance i can buy you a coffee?

**Comment by ivodolenc** [comment]
> i have successfully added rias plugin into my project!

@PavelZhuravlev that's awesome! 🎉

Actually, would you be interested in sharing an example with the `rias` plugin? Maybe something simple like [this](https://github.com/ivodolenc/nuxt-lazysizes/tree/master/examples/basic)? It can be a `PR` or link to `repo/codesandbox`.

I would be more than happy to merge/share it here (in the `examples` folder) so we can improve examples and maybe help someone to get started easier.

> Is there any chance i can buy you a coffee?

Nice gesture, I appreciate it 😉  You can try it [here](https://ko-fi.com/ivodolenc) or [here](https://paypal.me/ivodolenc).

And thanks for your interest and support, it means a lot. 👍

**Comment by PavelZhuravlev** [comment]
@ivodolenc, Actually I'm developing personal [Blog Starter](https://github.com/PavelZhuravlev/strapi-starter-nuxt-blog-kit) using Nuxt.js and Strapi upon the Strapi official fork.
I'm using nuxt-lazysizes as a part of my logic to maintain [Cloudinary](https://cloudinary.com/) images in the project.

Having said that, I assume that my example is very specific and I am not sure that it might fit well for your `examples/showcases`, but thank you anyway!


> You can try it here or here

Thanks, done!  😉

**Comment by ivodolenc** [comment]
@PavelZhuravlev ah I see. Ok, thanks for coffees 😉 ☕ Have a nice day! Cheers 👋
