### ISSUE TITLE
Version 1.2.1 breaks SSR

### ISSUE THREAD

**Issue by MateiNenciu** [ivodolenc/nuxt-lazysizes#7]
Throws error "window is not defined". I've made a repo to easily reproduce the error: https://github.com/MateiNenciu/nuxt-lazy-sizes-ssr-issue

  I believe this issue appeared when you removed the ssr: false option from plugin.

**Comment by ivodolenc** [comment]
This is due to the `nativeLoading` plugin, I forgot to put the plugins inside `process.client`. Thanks for the report 👍

**Comment by ivodolenc** [comment]
Fixed in `v1.2.2` ([eb2d70c](https://github.com/ivodolenc/nuxt-lazysizes/commit/eb2d70cdc05a0d02b474fd14ef0204e529755290))
